# Generated by Django 5.0.2 on 2024-12-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='count_question',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='score',
            field=models.FloatField(default=100.0),
        ),
    ]
