# Generated by Django 5.0.2 on 2024-12-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_exam_questions'),
        ('question', '0005_alter_subsubject_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('attempts_count', models.PositiveIntegerField(default=1)),
                ('count_question', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('score', models.FloatField(default=100.0)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('questions', models.ManyToManyField(blank=True, to='question.question')),
                ('subjects', models.ManyToManyField(to='question.subject')),
                ('subsubjects', models.ManyToManyField(to='question.subsubject')),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
