# Generated by Django 5.0.2 on 2024-12-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_test_delete_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('oraliq_nazorat', 'Oraliq nazorat'), ('joriy_nazorat', 'Joriy nazorat'), ('imtixon', 'Imtixon')], default='joriy_nazorat', max_length=50),
        ),
    ]
