# Generated by Django 5.0.2 on 2024-12-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_test_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
