# Generated by Django 5.0.2 on 2024-12-14 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_rename_time_test_duration_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='questions',
        ),
    ]
