# Generated by Django 5.0.2 on 2024-12-13 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_subsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sub_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.subsubject'),
        ),
    ]
