# Generated by Django 5.0.2 on 2024-12-13 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_question_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubjects', to='question.subject'),
        ),
    ]
