# Generated by Django 5.0.2 on 2024-12-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_alter_subsubject_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='language',
            field=models.CharField(choices=[('uz', 'Uz'), ('ru', 'Ru')], default='uz', max_length=2),
        ),
    ]
